openapi: 3.0.0
info:
  title: Test API docs
  version: v1
  description: Dummy description
servers:
  - url: http://localhost:1337
    description: Local test server
tags:
  - name: common
paths:
  /foo/bar:
    get:
      tags:
        - common
      summary: Test API route
      parameters:
        - in: query
          name: query
          schema:
            type: "string"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  users:
                    type: "array"
                    items:
                      type: "object"
                      properties:
                        name:
                          type: "string"
                        role:
                          type: "string"
                          enum:
                            - DEFAULT
                            - ADMIN
                      required:
                        - name
                        - role
                required:
                  - users
